Daily challenge endpoints
santoshernandezr/como-se-dice pull request #1
Opened 2024-07-31 00:56 UTC by santoshernandezr

This PR is for the daily challenge functionality. The major changes include: 

1. When the user goes into the daily challenge page, check if they have completed the daily challenge. If so, render the game, else show them the completed daily challenge page.
2. Use cron job in the server to call two endpoints at midnight everyday. One endpoint to update the daily challenge words, and the second endpoint to reset all users daily challenge boolean (if they completed it) to false, so they can play the next day.
3. Endpoints to help with daily challenge tasks.

2024-08-04 16:42 UTC, grrdsoto commented on client/src/components/common/profiilePictureGrid.jsx
profi*lePictureGrid.jsx

2024-08-04 16:45 UTC, grrdsoto requested changes
need to add node_modules to gitignore

2024-08-06 00:17 UTC, santoshernandezr commented
> need to add node_modules to gitignore

added

2024-08-06 00:17 UTC, santoshernandezr commented on client/src/components/common/profiilePictureGrid.jsx
What does this mean?

2024-08-11 15:32 UTC, merged